### ISSUE TITLE
Create initial API keys

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Clock-of-Change-API#13]
**Problem:**
Apparently, valid API keys are a table in the database. I don't know how to seed the database with an API key.

**Solution:**
You could create a seeder script, so I can `docker-compose exec db ./seed.sh` and have some API keys in the log output maybe.

**Comment by roschaefer** [comment]
@matthib ah, there is already an issue for this.

**Comment by matthib** [comment]
As mentioned by @roschaefer, the creation of API keys need to be mentioned in the Readme.md - whether they need to be created manually or automatically.
